[package]
name = "brix_processor"
version = "0.1.0"
authors = ["Miapolis <41233357+Miapolis@users.noreply.github.com>"]
edition = "2018"

[dependencies]
brix_errors = { path = "../../crates/brix_errors" }
serde = { version = "1.0.126", features = ["derive"] }
handlebars = "4.1.0"
serde_json = "1.0.64"
titlecase = "1.1.0"
convert_case = "0.4.0"

