[package]
name = "brix_commands"
version = "0.1.0"
authors = [
  "Ethan Lerner <ethan@lerners.io>",
  "Caleb Cushing <xenoterracide@gmail.com>"
]
edition = "2018"

[dependencies]
brix_common = { path = "../brix_common" }
brix_errors = { path = "../brix_errors" }
brix_processor = { path = "../brix_processor" }
log = "^0"
serde = { version = "1.0.126", features = ["derive"] }
fancy-regex = "0.7.0"
validator = { version = "^0", features = ["derive"] }
dialoguer = "^0"
execute = "0.2.9"
colored = "2.0.0"

[dev-dependencies]
spectral = "^0"
pretty_assertions = "^0"
maplit = "1.0.2"
