[package]
name = "brix_commands"
version = "0.1.0"
authors = ["Miapolis <41233357+Miapolis@users.noreply.github.com>", "Caleb Cushing <xenoterracide@gmail.com>"]
edition = "2018"

[dependencies]
log = "^0"
brix_errors = { path = "../../crates/brix_errors" }
regex = "^1"
validator = { version = "^0", features = ["derive"] }
dialoguer = "^0"

[dev-dependencies]
spectral = "^0"
pretty_assertions = "^0"
