[package]
name = "brix_errors"
version = "0.1.0"
authors = ["Miapolis <41233357+Miapolis@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
serde_yaml = "0.8.17"
handlebars = "4.1.0"
validator = "^0"
regex = "^1"
